"""Regenerate the CLI command inventory from installed parser definitions."""

import argparse
from pathlib import Path

from edge_delegate.cli import build_parser as core_parser
from edge_delegate_lab.cli import build_parser as lab_parser

DESTINATION = Path(__file__).resolve().parents[1] / "docs" / "reference" / "cli.md"


def render() -> str:
    lines = [
        "# Python command reference",
        "",
        "[Documentation home](../README.md) | [Tutorial](../try-it.md) | [Results](results.md)",
        "",
        "<!-- Generated by scripts/generate_cli_reference.py; do not edit the inventory. -->",
        "",
        "This inventory comes from the installed Python CLI parsers. Run a command with --help for",
        "its options and defaults. Presence here means implemented, not production-qualified.",
        "For setup, artifacts and workflows use the [development runbook](../development-runbook.md).",
        "For edgectl and the Rust host, use the [execution-service reference](execution-service.md).",
        "",
    ]
    for executable, factory in (("edge-delegate", core_parser), ("edge-delegate-lab", lab_parser)):
        parser = factory()
        action = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
        descriptions = {a.dest: a.help for a in action._choices_actions}
        lines.extend([f"## {executable}", "", "| Command | Parser description |", "| --- | --- |"])
        for name in sorted(action.choices):
            description = (
                descriptions.get(name) or action.choices[name].description or "See --help."
            )
            description = " ".join(description.split()).replace("|", r"\|")
            lines.append(f"| \x60{executable} {name}\x60 | {description} |")
        lines.append("")
    lines.extend(
        [
            "## Software device process",
            "",
            "\x60edge-delegate-device --help\x60 describes the standalone Unix-socket temperature emulator.",
            "It stays running while awaiting requests; that is normal server behavior, not model inference.",
            "Use the managed lab run workflow for first use instead of manually coordinating terminals.",
            "",
            "## Not implemented as Python core commands",
            "",
            "The Python core has no serve/request/status/reconcile/cancel service commands.",
            "The lab reconcile command is receipt recovery, not a supervised public service.",
            "The control SDK has status/reconcile methods but no whole-request cancellation API.",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the reference is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != expected:
            raise SystemExit("CLI reference is stale; run python scripts/generate_cli_reference.py")
        print("CLI reference matches the installed parsers.")
    else:
        DESTINATION.write_text(expected, encoding="utf-8")
        print(f"Updated {DESTINATION}")


if __name__ == "__main__":
    main()
