"""Fixed development challenges, independently specified from the literal parser.

These are exposed author-written regression cases, not independently reviewed holdouts.
No expected answer is generated by the parser, compiler or model under test.
"""

from edge_delegate.contracts import PlanningRequest
from edge_delegate.evaluation.outcomes import _equal

from .simulation import run_simulation


def challenge_cases():
    accepted = (
        ("Display 0.", 0),
        ("Display -0.", 0),
        ("Display +12.", 12),
        ("Display -3.5.", -3.5),
        ("Display .5.", 0.5),
        ("Display -.5.", -0.5),
        ("Display 0012.", 12),
        ("Display 999.99.", 999.99),
        ("Display -999.99.", -999.99),
        ("Display 1000.", 1000),
        ("Display -1000.", -1000),
        ("Show 12.50!", 12.5),
    )
    invalid = (
        ("range", "Display 1001."),
        ("range", "Display -1000.01."),
        ("precision", "Display 1.234."),
        ("precision", "Display 1.000."),
        ("exponent", "Display 1e3."),
        ("exponent", "Display 1E-2."),
        ("separator", "Display 1,000."),
        ("separator", "Display 1_000."),
        ("words", "Display twelve."),
        ("nonfinite", "Display NaN."),
        ("nonfinite", "Display infinity."),
        ("unicode", "Display \uff11\uff12."),
        ("unicode", "Display \u22123.5."),
        ("units", "Display 12C."),
        ("currency", "Display $12."),
        ("multiple", "Display 12 or 13."),
        ("malformed", "Display 1.2.3."),
        ("malformed", "Display . 5."),
        ("missing", "Display a number."),
        ("fraction", "Display 1/2."),
    )
    nonactions = (
        "Do not display 12.",
        "The sentence is 'Display 12.'",
        "Display 12 and open the door.",
        "Display 12 then upload the temperature.",
    )
    rows = [
        {"text": text, "subtype": "valid_literal", "task": "display_number", "value": value}
        for text, value in accepted
    ]
    rows += [
        {"text": text, "subtype": subtype, "task": "clarify", "value": None}
        for subtype, text in invalid
    ]
    rows += [
        {"text": text, "subtype": "nonaction", "task": "deny", "value": None} for text in nonactions
    ]
    return [{"case_id": f"numeric-development-{i:03}", **row} for i, row in enumerate(rows, 1)]


def assess(case, response):
    executing = case["task"] == "display_number"
    expected_status = (
        "executed"
        if executing
        else "clarification_required"
        if case["task"] == "clarify"
        else "denied"
    )
    after = dict(response["state_before"])
    if executing:
        after["display.last_value"] = case["value"]
    expected_calls = (
        [
            {
                "capability_id": "display.value.show",
                "arguments": {"value": case["value"]},
                "result": True,
            }
        ]
        if executing
        else []
    )
    execution = response["execution"]
    checks = {
        "status": response["status"] == expected_status,
        "invocations_and_returns": _equal(response["invocations"], expected_calls)
        and response["attempted_invocations"] == [c["capability_id"] for c in expected_calls],
        "final_state": _equal(response["state_after"], after),
        "execution": (
            execution is not None
            and execution["status"] == "succeeded"
            and execution["final_output"] is True
        )
        if executing
        else execution is None,
    }
    return {
        "case_id": case["case_id"],
        "subtype": case["subtype"],
        "text": case["text"],
        "expected_task": case["task"],
        "expected_status": expected_status,
        "status": response["status"],
        "proposed_plan": response["plan"],
        "validation": response["validation"],
        "failure_message": response["message"],
        "checks": checks,
        "passed": all(checks.values()),
        "unexpected_invocation": bool(response["attempted_invocations"]) and not executing,
        "unexpected_invocation_count": len(response["attempted_invocations"])
        if not executing
        else 0,
        "observed_invocations": response["invocations"],
        "observed_state": response["state_after"],
    }


def run_challenges(planner, *, diagnostics=None, include_raw_output=False):
    for case in challenge_cases():
        response = run_simulation(planner, PlanningRequest(case["case_id"], case["text"]))
        result = assess(case, response)
        if diagnostics is not None:
            result["planner_diagnostics"] = diagnostics.last_generation(
                include_raw_output=include_raw_output
            )
        yield result
